import { fileURLToPath, URL } from 'node:url'
import { readFileSync, readdirSync, writeFileSync, mkdirSync } from 'node:fs'
import { join, dirname } from 'node:path'
import type { Plugin } from 'vite'
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import matter from 'gray-matter'

const ROOT = new URL('./', import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, '$1')
const POSTS_DIR = join(ROOT, 'src/content/posts')
const GENERATED_FILE = join(ROOT, 'src/__generated_routes.ts')

/**
 * gray-matter 把 YAML 时间戳解析成 Date 对象(UTC),
 * 但前端要按本地时间解释,这里把所有 Date 递归替换成本地字符串。
 * 类型上无法精确推导递归结构,直接用 any。
 */
function fixDates(obj: any): any {
  if (obj === null || obj === undefined) return obj
  if (obj instanceof Date) {
    const y = obj.getUTCFullYear()
    const m = String(obj.getUTCMonth() + 1).padStart(2, '0')
    const d = String(obj.getUTCDate()).padStart(2, '0')
    const hh = String(obj.getUTCHours()).padStart(2, '0')
    const mm = String(obj.getUTCMinutes()).padStart(2, '0')
    const ss = String(obj.getUTCSeconds()).padStart(2, '0')
    return `${y}-${m}-${d} ${hh}:${mm}:${ss}`
  }
  if (Array.isArray(obj)) return obj.map(fixDates)
  if (typeof obj === 'object') {
    const out: Record<string, unknown> = {}
    for (const [k, v] of Object.entries(obj)) out[k] = fixDates(v)
    return out
  }
  return obj
}

function pad(n: number): string {
  return n.toString().padStart(2, '0')
}

function buildUrl(slug: string, date: string): string {
  const d = new Date(date)
  if (Number.isNaN(d.getTime())) return `/posts/${slug}/`
  return `/${d.getFullYear()}/${pad(d.getMonth() + 1)}/${pad(d.getDate())}/${slug}/`
}

function isTrue(v: unknown): boolean {
  return v === true || v === 'true' || v === '是' || v === 1
}

interface GeneratedPost {
  title: string
  slug: string
  date: string
  tags: string[]
  categories?: string | string[]
  cover?: string
  top?: boolean
  description?: string
  url: string
}

function buildRoutes(): { posts: GeneratedPost[]; tags: string[] } {
  const posts: GeneratedPost[] = []
  for (const file of readdirSync(POSTS_DIR)) {
    if (!file.endsWith('.md')) continue
    const raw = readFileSync(join(POSTS_DIR, file), 'utf-8')
    const { data } = matter(raw)
    const fixed = fixDates(data)
    const slug = file.replace(/\.md$/, '')
    const date = fixed.date ? new Date(fixed.date as string).toISOString() : new Date().toISOString()
    posts.push({
      title: (fixed.title as string) || slug,
      slug,
      date,
      tags: Array.isArray(fixed.tags) ? (fixed.tags as string[]) : [],
      categories: fixed.categories as string | string[] | undefined,
      cover: fixed.cover as string | undefined,
      top: isTrue(fixed.top),
      description: (fixed.description as string) || '',
      url: buildUrl(slug, date),
    })
  }
  posts.sort((a, b) => +new Date(b.date) - +new Date(a.date))
  const tagSet = new Set<string>()
  for (const p of posts) p.tags.forEach((t) => tagSet.add(t))
  return { posts, tags: [...tagSet].sort() }
}

function mdAsData(): Plugin {
  return {
    name: 'md-as-data',
    enforce: 'pre',
    transform(_code: string, id: string) {
      if (!id.endsWith('.md') || id.includes('node_modules')) return null
      const raw = readFileSync(id, 'utf-8')
      const parsed = matter(raw)
      const fixed = fixDates(parsed.data)
      const code = `export default ${JSON.stringify({
        data: fixed,
        content: parsed.content,
      })}`
      return { code, map: null }
    },
  }
}

function generateRoutes(): Plugin {
  return {
    name: 'generate-routes',
    buildStart() {
      const { posts, tags } = buildRoutes()
      const code = `// AUTO-GENERATED by vite.config.ts (buildStart hook).
// 目的:让所有文章 URL 在客户端 bundle 里可用,避免被 Vite tree-shake。

export interface GeneratedPostMeta {
  title: string
  slug: string
  date: string
  tags: string[]
  categories?: string | string[]
  cover?: string
  top?: boolean
  description?: string
  url: string
}

export const generatedPosts: GeneratedPostMeta[] = ${JSON.stringify(posts, null, 2)}

export const generatedTags: string[] = ${JSON.stringify(tags, null, 2)}
`
      mkdirSync(dirname(GENERATED_FILE), { recursive: true })
      writeFileSync(GENERATED_FILE, code, 'utf-8')
      console.log(`[routes] generated ${posts.length} posts, ${tags.length} tags -> ${GENERATED_FILE.replace(ROOT, '')}`)
    },
  }
}

function setHtmlLang(lang: string): Plugin {
  return {
    name: `set-html-lang-${lang}`,
    transformIndexHtml: {
      order: 'pre',
      handler(html: string): string {
        return html.replace(
          /<html(\s[^>]*)?>/i,
          (match: string, attrs?: string) => {
            const a = attrs || ' '
            if (/lang=/i.test(a)) {
              return '<html' + a.replace(/lang="[^"]*"/i, 'lang="' + lang + '"') + '>'
            }
            return `<html${a} lang="${lang}">`
          },
        )
      },
    },
  }
}

export default defineConfig({
  plugins: [
    generateRoutes(),
    vue(),
    mdAsData(),
    setHtmlLang('zh-CN'),
  ],
  resolve: {
    alias: { '@': fileURLToPath(new URL('./src', import.meta.url)) },
  },
  base: '/',
  server: { host: '127.0.0.1', port: 5173, strictPort: false },
  preview: { host: '127.0.0.1', port: 5050, strictPort: false },
  // @ts-expect-error - ssgOptions 是 vite-ssg 扩展
  ssgOptions: { script: 'async', formatting: 'minify', crittersOptions: false },
})

