export const site = {
  title: 'LiangYouBiao 的博客',
  shortTitle: 'LiangYouBiao',
  brandIcon: '🌿',
  description: '记录学习与生活的点滴',
  author: 'LiangYouBiao',
  url: 'https://liangyoubiao.github.io',
  githubUrl: 'https://github.com/liangyoubiao',
  language: 'zh-CN',
  avatar: '/medias/avatar.webp',
  subtitle: [
    'LiangYouBiao 的博客',
    '记录学习与生活的点滴',
    '保持好奇,持续输出',
    '代码 · 阅读 · 骑行 · 滑雪',
    'Stay hungry, stay foolish',
  ],
  dream: {
    title: '我的梦想',
    text: '人与人之间的核心差距，从来不在想法的多少，而在执行力的强弱。无论是个人成长的比拼，还是社会资源的争夺，最终拼的都是谁能把想法落地，谁能把行动坚持到底。强大的执行力，意味着面对挑战时能快速行动，遭遇挫折时能坚持到底，在一次次攻坚克难中稳步前行。当别人选择放弃时，你依然坚守；当别人止步不前时，你继续突破',
  },
  banners: [
    '/medias/banner/0.webp',
    '/medias/banner/1.webp',
    '/medias/banner/2.webp',
    '/medias/banner/3.webp',
    '/medias/banner/4.webp',
    '/medias/banner/5.webp',
    '/medias/banner/6.webp',
  ],
  bannerButtons: [
    { text: '开始阅读', icon: '↓', href: '#articles', primary: true },
    { text: 'GitHub', icon: '', href: 'https://github.com/liangyoubiao', primary: false },
  ],
  nav: [
    { name: '首页', path: '/' },
    { name: '归档', path: '/archives/' },
    { name: '日历', path: '/calendar/' },
    { name: '分类', path: '/categories/' },
    { name: '标签', path: '/tags/' },
    { name: '友链', path: '/friends/' },
    { name: '小工具', path: '/demos/' },
    { name: '关于', path: '/about/' },
    { name: '留言', path: '/contact/' },
  ],
  socials: [
    { name: 'GitHub', url: 'https://github.com/liangyoubiao', icon: 'GitHub' },
  ],
}

